title: Astro Club IITK
description: A comprehensive guide to Astronomy Club IITK
theme: just-the-docs
url: https://astroclubiitk.github.io/wiki
repository: astroclubiitk/wiki

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: '/assets/images/favicon.ico'

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Back to top link
back_to_top: false
back_to_top_text: 'Back to top'

# For callouts
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

socials:
  github: 'https://github.com/astroclubiitk'
  facebook: 'https://www.facebook.com/AstroClubIITK/'
  instagram: 'https://instagram.com/astroclub.iitk'
  youtube: 'https://www.youtube.com/c/AstroclubIITK'
  linkedin: 'https://www.linkedin.com/company/astroclubiitk/'
  x: 'https://x.com/astroclubiitk'
  discord: 'https://discord.gg/xTbxM6RthY'
  email: 'astroclub@iitk.ac.in'

# LaTeX rendering via "katex" (KaTeX, default) or "mathjax" (MathJax) or "none" / "off" (NO rendering)
mathjax: true
latex: mathjax
compress_html:
  blanklines: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: 'Edit this page on GitHub'
gh_edit_repository: 'https://github.com/astroclubiitk/wiki' # the github URL for your repo
gh_edit_branch: 'main' # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: 'tree' # "tree" or "edit" if you want the user to jump into the editor immediately

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/{%
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - '*.gemspec'
  - '*.gem'
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
